[build]
target = "x86_64-unknown-none"
incremental = true

[env]
RUSTC_BOOTSTRAP = { value = "1", force = true }
CARGO_UNSTABLE_JSON_TARGET_SPEC = { value = "true", force = true }
CARGO_UNSTABLE_UNSTABLE_OPTIONS = { value = "true", force = true }

[profile.dev]
incremental = true
debug-assertions = true

[profile.release]
incremental = true
debug-assertions = false

[alias]
verify = "v build"