//! Whether the hardware is walking this tree, as a tracked fact rather than a
//! type.
//!
//! SVSM distinguishes an installed page table from an inactive one by giving
//! them different types, which forces every operation to be written twice --
//! once per state -- or generated by a macro. Here the distinction is a linear
//! ghost token instead: one page-table type, one copy of each operation, and
//! the operations that may only run on a tree nobody is walking say so in their
//! `requires`.
//!
//! # What is proved and what is assumed
//!
//! Becoming installed is *proved*: [`PTInstallState::mark_installed`] takes a
//! borrow of the paging-root register token and checks that it names this
//! tree's root. Becoming uninstalled cannot be proved from one register: a
//! tree is inactive only when no CPU's root register names it, and this crate
//! models one register state. [`PTInstallState::mark_uninstalled`] is
//! therefore where the embedder promises that, and it is the only assumption
//! in this file.
use core::marker::PhantomData;

use machine_model::arch::x86_64::Cr3;
use machine_model::register::RustRegisterPointsTo;
use vstd::prelude::*;

use crate::arch::x86_64::reg_contract::cr3_root_frame;
use crate::structs::address::{Address, PhysAddr};
use crate::structs::arch_contract::ArchPagingMeta;

verus! {

/// A linear claim about one tree: which frame roots it, and whether the
/// hardware is walking it.
///
/// The fields are private, so the only way to obtain one is
/// [`PTInstallState::new_uninstalled`], which the owner of the root frame
/// calls once. Linearity is what gives the claim its force: a handle holds
/// exactly one, so there is no second token to contradict it.
pub tracked struct PTInstallState<A: ArchPagingMeta> {
    ghost root_frame: usize,
    ghost installed: bool,
    ghost arch: PhantomData<A>,
}

impl<A: ArchPagingMeta> PTInstallState<A> {
    pub closed spec fn root_frame(self) -> usize {
        self.root_frame
    }

    /// Whether the hardware may be walking this tree. An operation that
    /// reclaims interior pages requires this to be false.
    pub closed spec fn installed(self) -> bool {
        self.installed
    }

    /// The claim the owner of a fresh root frame starts from: a tree nobody
    /// has installed yet.
    ///
    /// Sound because the caller must own the root frame's memory to build the
    /// handle this token goes into, and a frame the allocator just handed out
    /// is in no register.
    pub proof fn new_uninstalled(root_frame: usize) -> (tracked ret: Self)
        ensures
            ret.root_frame() == root_frame,
            !ret.installed(),
    {
        PTInstallState { root_frame, installed: false, arch: PhantomData }
    }

    /// Records that the paging-root register names this tree.
    ///
    /// Proved, not assumed: the register token says what the register holds.
    pub fn mark_installed(
        Tracked(state): Tracked<&mut PTInstallState<A>>,
        root: PhysAddr,
        Tracked(cr3): Tracked<&RustRegisterPointsTo<Cr3>>,
    )
        requires
            old(state).root_frame() == root@,
            cr3_root_frame::<A>(cr3.value()) == root@,
        ensures
            final(state).root_frame() == old(state).root_frame(),
            final(state).installed(),
    {
        proof {
            state.installed = true;
        }
    }

    /// Records that no CPU's paging-root register names this tree any more.
    ///
    /// TRUSTED. One register state cannot witness the absence of this root
    /// from every CPU, so the embedder carries that argument: it must have
    /// loaded another root everywhere this one was loaded, and completed the
    /// shootdown that makes the change visible.
    pub proof fn mark_uninstalled(tracked state: &mut PTInstallState<A>)
        ensures
            final(state).root_frame() == old(state).root_frame(),
            !final(state).installed(),
    {
        state.installed = false;
    }
}

} // verus!
