name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Build checking
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install depdendencies
        run: |
            cargo install --path tools/cargo-v
            cargo install --path tools/verus-rustc
            cargo-v prepare-verus

      - name: Build
        run: cd source/verismo && cargo v build
