name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: fetch verus via metadata
        run: |
            source ../tools/v-ci-setup.sh
            echo "VERUS_PATH=$(echo $VERUS_PATH)" >> $GITHUB_ENV
        working-directory: source


      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ${{ env.VERUS_PATH }}/source/target-verus
          workspaces: |
            ${{ github.workspace }}/source -> target
            ${{ env.VERUS_PATH }}/source -> target
            ${{ env.VERUS_PATH }}/tools/vargo -> target

      - name: Install depdendencies
        run: |
            cargo install --path tools/cargo-v
            cargo install --path tools/verus-rustc
            cargo-v prepare-verus

      - name: Build
        run: cd source/verismo && cargo v build

      - name: Fmt
        run: cargo fmt
        working-directory: tools/cargo-v

      - name: Fmt
        run: cargo fmt
        working-directory: tools/verus-rustc

      - name: Fmt verus code
        run: ./tools/fmt.sh

