name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: verification
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install specified rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-12-22
          target: x86_64-unknown-none
          profile: minimal

      - name: fetch verus via metadata
        working-directory: source
        run: |
            source ../tools/v-ci-setup.sh
            echo "VERUS_PATH=$(echo $VERUS_PATH)" >> $GITHUB_ENV

      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ${{ env.VERUS_PATH }}/source/target-verus
          workspaces: |
            ${{ github.workspace }}/source -> target
            ${{ env.VERUS_PATH }}/source -> target
            ${{ env.VERUS_PATH }}/tools/vargo -> target

      - name: Install depdendencies
        run: ./tools/activate.sh
  
      - name: Build
        working-directory: source/verismo
        run: cargo v build

      - name: Fmt
        run: cargo fmt
        working-directory: tools/cargo-v

      - name: Fmt
        run: cargo fmt
        working-directory: tools/verus-rustc

      - name: Fmt verus code
        run: ./tools/fmt.sh --check

