name: Rust Linter

on:
  push:
    branches: [ "pg-isolated" ]
  pull_request:
    branches: [ "pg-isolated" ]

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt

      - name: Run `cargo fmt -- --check`
        run: cargo fmt --check
        working-directory: source
